### ISSUE TITLE
RpcError: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

### ISSUE THREAD

**Issue by PhucDao-PLab** [Leouarz/avail-js#1]
Hi team! I try to use tranfer example in repo but it seem not working:
Here is my code and issues:
`
import { getDecimals, initialize, formatNumberToBalance, getKeyringFromSeed, isValidAddress } from "avail-js-sdk"

const main = async () => {
  try {
    const seed = "seedHided" // Put a seed with some funds here
    const recipient = "addressHided" // Put recipient here

    if (!isValidAddress(recipient)) throw new Error("Invalid Recipient")

    const api = await initialize()
    const keyring = getKeyringFromSeed(seed)
    const options = { app_id: 0, nonce: -1 }
    const decimals = getDecimals(api)
    const amount = formatNumberToBalance(1, decimals)

    await api.tx.balances.transfer(recipient, amount).signAndSend(keyring, options)

    process.exit(0)
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}
main()
`
error:

2023-11-15 17:10:57 PORTABLEREGISTRY: Unable to determine runtime Call type, cannot inspect sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic
2023-11-15 17:10:58        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
RpcError: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
    at checkError (/home/phucdao/avail2/avail-js/examples/transfer/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:23:15)
    at RpcCoder.decodeResponse (/home/phucdao/avail2/avail-js/examples/transfer/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:41:9)
    at WsProvider.__internal__onSocketMessageResult (/home/phucdao/avail2/avail-js/examples/transfer/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:131:55)
    at WsProvider.__internal__onSocketMessage (/home/phucdao/avail2/avail-js/examples/transfer/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:120:24)
    at callListener (/home/phucdao/avail2/avail-js/examples/transfer/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/phucdao/avail2/avail-js/examples/transfer/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/home/phucdao/avail2/avail-js/examples/transfer/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:514:28)

**Comment by harodggg** [comment]
You should update dependencies, I also encountered this problem, updating dependencies is effective.
